
INFO:root:load_data. dataset_name = mnist
INFO:root:loading data...
INFO:root:finished the loading data
INFO:root:create_model. model_name = lr, output_dim = 10
INFO:root:LogisticRegression + MNIST
INFO:root:LogisticRegression(
  (linear): Linear(in_features=784, out_features=10, bias=True)
)
INFO:root:############setup_clients (START)#############
INFO:root:self.local_sample_number = 17
INFO:root:self.local_sample_number = 72
INFO:root:self.local_sample_number = 22
INFO:root:self.local_sample_number = 14
INFO:root:self.local_sample_number = 14
INFO:root:self.local_sample_number = 13
INFO:root:self.local_sample_number = 12
INFO:root:self.local_sample_number = 28
INFO:root:self.local_sample_number = 14
INFO:root:self.local_sample_number = 65
INFO:root:############setup_clients (END)#############
INFO:root:################Communication round : 0
INFO:root:client_indexes = [993 859 298 553 672 971  27 231 306 706]
INFO:root:client_indexes = [993 859 298 553 672 971  27 231 306 706]
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.295648
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.096707
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.321296
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.182066
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.202689
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.245562
INFO:root:Client Index = 0	Epoch: 0	Loss: 1.998486
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.230462
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.085529
INFO:root:Client Index = 0	Epoch: 0	Loss: 2.038341
INFO:root:################local_test_on_all_clients : 0
INFO:root:{'training_acc': 0.24505384016606124, 'training_loss': 2.255416232698172}
INFO:root:{'test_acc': 0.24637091303757971, 'test_loss': 2.254437982639809}
Traceback (most recent call last):
  File "./main_fedavg.py", line 322, in <module>
    fedavgAPI.train()
  File "/home/cps/Desktop/FedML_CPS/fedml_api/standalone/fedavg/fedavg_api.py", line 86, in train
    logging.info("################running time: {}".format(time.time()-start))
NameError: name 'start' is not defined